<?php


namespace App\Helpers\Deployer;


use App\Helpers\Deployer\Classes\Deploy;
use App\Models\DomainVolume;

class V2 extends Deploy
{
    public static function run(string $cmd)
    {
        parent::run($cmd); // TODO: Change the autogenerated stub
    }

    public static function setup(string $domain, DomainVolume $pvc, bool $isPersonal = false, string $customerDomain = '')
    {
        // TODO: Implement setup() method.
    }

    public static function create()
    {
        // TODO: Implement create() method.
    }

    public static function install(DomainVolume $pvc, string $domain): void
    {
        parent::install($pvc, $domain); // TODO: Change the autogenerated stub
    }
}